# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

  # 🔥 只检查 Ruby 文件
  Include:
    - 'app/**/*.rb'

  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'app/admin/**/*'      # ActiveAdmin
    - 'app/views/**/*'      # ERB 不检查
    - 'app/assets/**/*'     # CSS/JS 不检查